import { DailyWord, QwertyTypeArray } from "../types";
import { Colors } from "../../ui-kit";


export const _QWERTY: QwertyTypeArray = [
    [
        { letter: 'q', color: Colors.white, textColor: Colors.black },
        { letter: 'w', color: Colors.white, textColor: Colors.black },
        { letter: 'e', color: Colors.white, textColor: Colors.black },
        { letter: 'r', color: Colors.white, textColor: Colors.black },
        { letter: 't', color: Colors.white, textColor: Colors.black },
        { letter: 'y', color: Colors.white, textColor: Colors.black },
        { letter: 'u', color: Colors.white, textColor: Colors.black },
        { letter: 'i', color: Colors.white, textColor: Colors.black },
        { letter: 'o', color: Colors.white, textColor: Colors.black },
        { letter: 'p', color: Colors.white, textColor: Colors.black },
    ],
    [
        { letter: 'a', color: Colors.white, textColor: Colors.black },
        { letter: 's', color: Colors.white, textColor: Colors.black },
        { letter: 'd', color: Colors.white, textColor: Colors.black },
        { letter: 'f', color: Colors.white, textColor: Colors.black },
        { letter: 'g', color: Colors.white, textColor: Colors.black },
        { letter: 'h', color: Colors.white, textColor: Colors.black },
        { letter: 'j', color: Colors.white, textColor: Colors.black },
        { letter: 'k', color: Colors.white, textColor: Colors.black },
        { letter: 'l', color: Colors.white, textColor: Colors.black },
        { letter: 'ñ', color: Colors.white, textColor: Colors.black },
    ],
    [
        { letter: '0', color: Colors.white, textColor: Colors.black },
        { letter: 'z', color: Colors.white, textColor: Colors.black },
        { letter: 'x', color: Colors.white, textColor: Colors.black },
        { letter: 'c', color: Colors.white, textColor: Colors.black },
        { letter: 'v', color: Colors.white, textColor: Colors.black },
        { letter: 'b', color: Colors.white, textColor: Colors.black },
        { letter: 'n', color: Colors.white, textColor: Colors.black },
        { letter: 'm', color: Colors.white, textColor: Colors.black },
        { letter: '1', color: Colors.white, textColor: Colors.black },
    ],
];


export const DAILY_WORDS: Array<DailyWord> = [
    { word: 'RIVER', useDate: '' },
    { word: 'night', useDate: '' },
    { word: 'hotel', useDate: '' },
    { word: 'tooth', useDate: '' },
    { word: 'bread', useDate: '' },
    { word: 'apple', useDate: '' },
    { word: 'video', useDate: '' },
    { word: 'cheek', useDate: '' },
    { word: 'actor', useDate: '' },
    { word: 'power', useDate: '' },
    { word: 'entry', useDate: '' },
    { word: 'movie', useDate: '' },
    { word: 'union', useDate: '' },
    { word: 'truth', useDate: '' },
    { word: 'drama', useDate: '' },
    { word: 'chest', useDate: '' },
    { word: 'buyer', useDate: '' },
    { word: 'owner', useDate: '' },
    { word: 'scene', useDate: '' },
    { word: 'piano', useDate: '' },
    { word: 'error', useDate: '' },
    { word: 'guest', useDate: '' },
    { word: 'queen', useDate: '' },
    { word: 'pizza', useDate: '' },
    { word: 'topic', useDate: '' },
    { word: 'depth', useDate: '' },
    { word: 'bonus', useDate: '' },
    { word: 'basis', useDate: '' },
    { word: 'shirt', useDate: '' },
    { word: 'skill', useDate: '' },
    { word: 'uncle', useDate: '' },
    { word: 'youth', useDate: '' },
    { word: 'heart', useDate: '' },
    { word: 'death', useDate: '' },
    { word: 'photo', useDate: '' },
    { word: 'thing', useDate: '' },
    { word: 'blood', useDate: '' },
    { word: 'world', useDate: '' },
    { word: 'event', useDate: '' },
    { word: 'media', useDate: '' },
    { word: 'ratio', useDate: '' },
    { word: 'salad', useDate: '' },
    { word: 'phone', useDate: '' },
    { word: 'steak', useDate: '' },
    { word: 'month', useDate: '' },
    { word: 'child', useDate: '' },
    { word: 'woman', useDate: '' },
    { word: 'honey', useDate: '' },
    { word: 'paper', useDate: '' },
    { word: 'virus', useDate: '' },
    { word: 'story', useDate: '' },
    { word: 'music', useDate: '' },
    { word: 'pause', useDate: '' },
    { word: 'burly', useDate: '' },
    { word: 'anger', useDate: '' },
    { word: 'dream', useDate: '' },
    { word: 'bawdy', useDate: '' },
    { word: 'dusty', useDate: '' },
    { word: 'fetch', useDate: '' },
    { word: 'flaky', useDate: '' },
    { word: 'count', useDate: '' },
    { word: 'overt', useDate: '' },
    { word: 'range', useDate: '' },
    { word: 'zebra', useDate: '' },
    { word: 'spicy', useDate: '' },
    { word: 'mouth', useDate: '' },
    { word: 'eager', useDate: '' },
    { word: 'cagey', useDate: '' },
    { word: 'thumb', useDate: '' },
    { word: 'water', useDate: '' },
    { word: 'space', useDate: '' },
    { word: 'groan', useDate: '' },
    { word: 'money', useDate: '' },
    { word: 'macho', useDate: '' },
    { word: 'cheat', useDate: '' },
    { word: 'shaky', useDate: '' },
    { word: 'brush', useDate: '' },
    { word: 'drink', useDate: '' },
    { word: 'windy', useDate: '' },
    { word: 'erect', useDate: '' },
    { word: 'waste', useDate: '' },
    { word: 'lunch', useDate: '' },
    { word: 'spiky', useDate: '' },
    { word: 'noise', useDate: '' },
    { word: 'delay', useDate: '' },
    { word: 'order', useDate: '' },
    { word: 'pedal', useDate: '' },
    { word: 'young', useDate: '' },
    { word: 'tired', useDate: '' },
    { word: 'taste', useDate: '' },
    { word: 'awful', useDate: '' },
    { word: 'rainy', useDate: '' },
    { word: 'plane', useDate: '' },
    { word: 'sniff', useDate: '' },
    { word: 'claim', useDate: '' },
    { word: 'spray', useDate: '' },
    { word: 'relax', useDate: '' },
    { word: 'flood', useDate: '' },
    { word: 'giant', useDate: '' },
    { word: 'roomy', useDate: '' },
    { word: 'aloof', useDate: '' },
    { word: 'jumpy', useDate: '' },
    { word: 'party', useDate: '' },
    { word: 'fruit', useDate: '' },
    { word: 'weigh', useDate: '' },
    { word: 'sulky', useDate: '' },
    { word: 'right', useDate: '' },
    { word: 'gusty', useDate: '' },
    { word: 'cycle', useDate: '' },
    { word: 'shock', useDate: '' },
    { word: 'serve', useDate: '' },
    { word: 'early', useDate: '' },
    { word: 'stamp', useDate: '' },
    { word: 'misty', useDate: '' },
    { word: 'magic', useDate: '' },
    { word: 'crime', useDate: '' },
    { word: 'train', useDate: '' },
    { word: 'jewel', useDate: '' },
    { word: 'crazy', useDate: '' },
    { word: 'clear', useDate: '' },
    { word: 'ready', useDate: '' },
    { word: 'close', useDate: '' },
    { word: 'puffy', useDate: '' },
    { word: 'blink', useDate: '' },
    { word: 'shade', useDate: '' },
    { word: 'stale', useDate: '' },
    { word: 'moldy', useDate: '' },
    { word: 'crack', useDate: '' },
    { word: 'occur', useDate: '' },
    { word: 'solid', useDate: '' },
    { word: 'wrong', useDate: '' },
    { word: 'greet', useDate: '' },
    { word: 'limit', useDate: '' },
    { word: 'shape', useDate: '' },
    { word: 'cheap', useDate: '' },
    { word: 'trust', useDate: '' },
    { word: 'north', useDate: '' },
    { word: 'doubt', useDate: '' },
    { word: 'ghost', useDate: '' },
    { word: 'faded', useDate: '' },
    { word: 'grate', useDate: '' },
    { word: 'robin', useDate: '' },
    { word: 'shelf', useDate: '' },
    { word: 'soggy', useDate: '' },
    { word: 'crush', useDate: '' },
    { word: 'coast', useDate: '' },
    { word: 'stick', useDate: '' },
    { word: 'super', useDate: '' },
    { word: 'cruel', useDate: '' },
    { word: 'snail', useDate: '' },
    { word: 'dolls', useDate: '' },
    { word: 'slope', useDate: '' },
    { word: 'kneel', useDate: '' },
    { word: 'reign', useDate: '' },
    { word: 'crash', useDate: '' },
    { word: 'scary', useDate: '' },
    { word: 'hurry', useDate: '' },
    { word: 'daffy', useDate: '' },
    { word: 'berry', useDate: '' },
    { word: 'queue', useDate: '' },
    { word: 'heavy', useDate: '' },
    { word: 'choke', useDate: '' },
    { word: 'curvy', useDate: '' },
    { word: 'avoid', useDate: '' },
    { word: 'lumpy', useDate: '' },
    { word: 'tiger', useDate: '' },
    { word: 'treat', useDate: '' },
    { word: 'smell', useDate: '' },
    { word: 'glass', useDate: '' },
    { word: 'slave', useDate: '' },
    { word: 'snake', useDate: '' },
    { word: 'scare', useDate: '' },
    { word: 'proud', useDate: '' },
    { word: 'laugh', useDate: '' },
    { word: 'guess', useDate: '' },
    { word: 'fence', useDate: '' },
    { word: 'nasty', useDate: '' },
    { word: 'spoil', useDate: '' },
    { word: 'pinch', useDate: '' },
    { word: 'juicy', useDate: '' },
    { word: 'prose', useDate: '' },
    { word: 'paste', useDate: '' },
    { word: 'brash', useDate: '' },
    { word: 'drain', useDate: '' },
    { word: 'round', useDate: '' },
    { word: 'fuzzy', useDate: '' },
    { word: 'upset', useDate: '' },
    { word: 'truck', useDate: '' },
    { word: 'quack', useDate: '' },
    { word: 'wacky', useDate: '' },
    { word: 'tease', useDate: '' },
    { word: 'rough', useDate: '' },
    { word: 'quick', useDate: '' },
    { word: 'quiet', useDate: '' },
    { word: 'rigid', useDate: '' },
    { word: 'flash', useDate: '' },
    { word: 'enter', useDate: '' },
    { word: 'shake', useDate: '' },
    { word: 'coach', useDate: '' },
    { word: 'jazzy', useDate: '' },
    { word: 'elbow', useDate: '' },
    { word: 'skirt', useDate: '' },
    { word: 'spark', useDate: '' },
    { word: 'label', useDate: '' },
    { word: 'godly', useDate: '' },
    { word: 'dirty', useDate: '' },
    { word: 'blush', useDate: '' },
    { word: 'wheel', useDate: '' },
    { word: 'teeny', useDate: '' },
    { word: 'yummy', useDate: '' },
    { word: 'fancy', useDate: '' },
    { word: 'angle', useDate: '' },
    { word: 'royal', useDate: '' },
    { word: 'gaudy', useDate: '' },
    { word: 'trace', useDate: '' },
    { word: 'smoke', useDate: '' },
    { word: 'brass', useDate: '' },
    { word: 'angry', useDate: '' },
    { word: 'clean', useDate: '' },
    { word: 'decay', useDate: '' },
    { word: 'wound', useDate: '' },
    { word: 'cheer', useDate: '' },
    { word: 'giddy', useDate: '' },
    { word: 'stare', useDate: '' },
    { word: 'harsh', useDate: '' },
    { word: 'shave', useDate: '' },
    { word: 'woozy', useDate: '' },
    { word: 'badge', useDate: '' },
    { word: 'green', useDate: '' },
    { word: 'boast', useDate: '' },
    { word: 'guide', useDate: '' },
    { word: 'argue', useDate: '' },
    { word: 'frame', useDate: '' },
    { word: 'cakes', useDate: '' },
    { word: 'nutty', useDate: '' },
    { word: 'smile', useDate: '' },
    { word: 'crate', useDate: '' },
    { word: 'smash', useDate: '' },
    { word: 'alarm', useDate: '' },
    { word: 'stone', useDate: '' },
    { word: 'grape', useDate: '' },
    { word: 'crook', useDate: '' },
    { word: 'steep', useDate: '' },
    { word: 'sheep', useDate: '' },
    { word: 'curve', useDate: '' },
    { word: 'faint', useDate: '' },
    { word: 'lucky', useDate: '' },
    { word: 'peace', useDate: '' },
    { word: 'dance', useDate: '' },
    { word: 'ocean', useDate: '' },
    { word: 'alike', useDate: '' },
    { word: 'jelly', useDate: '' },
    { word: 'kitty', useDate: '' },
    { word: 'empty', useDate: '' },
    { word: 'glove', useDate: '' },
    { word: 'strip', useDate: '' },
    { word: 'brief', useDate: '' },
    { word: 'haunt', useDate: '' },
    { word: 'scarf', useDate: '' },
    { word: 'voice', useDate: '' },
    { word: 'found', useDate: '' },
    { word: 'frogs', useDate: '' },
    { word: 'jeans', useDate: '' },
    { word: 'lying', useDate: '' },
    { word: 'humor', useDate: '' },
    { word: 'press', useDate: '' },
    { word: 'thank', useDate: '' },
    { word: 'furry', useDate: '' },
    { word: 'noisy', useDate: '' },
    { word: 'plain', useDate: '' },
    { word: 'messy', useDate: '' },
    { word: 'plate', useDate: '' },
    { word: 'wreck', useDate: '' },
    { word: 'strap', useDate: '' },
    { word: 'level', useDate: '' },
    { word: 'witty', useDate: '' },
    { word: 'admit', useDate: '' },
    { word: 'naive', useDate: '' },
    { word: 'stiff', useDate: '' },
    { word: 'burst', useDate: '' },
    { word: 'trite', useDate: '' },
    { word: 'plant', useDate: '' },
    { word: 'reach', useDate: '' },
    { word: 'cream', useDate: '' },
    { word: 'jolly', useDate: '' },
    { word: 'vague', useDate: '' },
    { word: 'linen', useDate: '' },
    { word: 'tasty', useDate: '' },
    { word: 'scrub', useDate: '' },
    { word: 'tense', useDate: '' },
    { word: 'hover', useDate: '' },
    { word: 'shrug', useDate: '' },
    { word: 'grade', useDate: '' },
    { word: 'alert', useDate: '' },
    { word: 'trade', useDate: '' },
    { word: 'loose', useDate: '' },
    { word: 'sassy', useDate: '' },
    { word: 'float', useDate: '' },
    { word: 'tight', useDate: '' },
    { word: 'brake', useDate: '' },
    { word: 'crowd', useDate: '' },
    { word: 'whirl', useDate: '' },
    { word: 'alive', useDate: '' },
    { word: 'raise', useDate: '' },
    { word: 'place', useDate: '' },
    { word: 'eight', useDate: '' },
    { word: 'touch', useDate: '' },
    { word: 'value', useDate: '' },
    { word: 'class', useDate: '' },
    { word: 'spade', useDate: '' },
    { word: 'aback', useDate: '' },
    { word: 'sound', useDate: '' },
    { word: 'carry', useDate: '' },
    { word: 'straw', useDate: '' },
    { word: 'silky', useDate: '' },
    { word: 'crawl', useDate: '' },
    { word: 'steer', useDate: '' },
    { word: 'teeth', useDate: '' },
    { word: 'ducks', useDate: '' },
    { word: 'ritzy', useDate: '' },
    { word: 'brick', useDate: '' },
    { word: 'house', useDate: '' },
    { word: 'black', useDate: '' },
    { word: 'force', useDate: '' },
    { word: 'brave', useDate: '' },
    { word: 'weary', useDate: '' },
    { word: 'scale', useDate: '' },
    { word: 'print', useDate: '' },
    { word: 'watch', useDate: '' },
    { word: 'happy', useDate: '' },
    { word: 'gabby', useDate: '' },
    { word: 'small', useDate: '' },
    { word: 'sharp', useDate: '' },
    { word: 'hands', useDate: '' },
    { word: 'short', useDate: '' },
    { word: 'taboo', useDate: '' },
    { word: 'slimy', useDate: '' },
    { word: 'itchy', useDate: '' },
    { word: 'silly', useDate: '' },
    { word: 'sheet', useDate: '' },
    { word: 'juice', useDate: '' },
    { word: 'light', useDate: '' },
    { word: 'waves', useDate: '' },
    { word: 'nifty', useDate: '' },
    { word: 'color', useDate: '' },
    { word: 'raspy', useDate: '' },
    { word: 'agree', useDate: '' },
    { word: 'chess', useDate: '' },
    { word: 'great', useDate: '' },
    { word: 'large', useDate: '' },
    { word: 'offer', useDate: '' },
    { word: 'birds', useDate: '' },
    { word: 'floor', useDate: '' },
    { word: 'tangy', useDate: '' },
    { word: 'rinse', useDate: '' },
    { word: 'ahead', useDate: '' },
    { word: 'kaput', useDate: '' },
    { word: 'shoes', useDate: '' },
    { word: 'cause', useDate: '' },
    { word: 'chalk', useDate: '' },
    { word: 'quill', useDate: '' },
    { word: 'bless', useDate: '' },
    { word: 'guard', useDate: '' },
    { word: 'verse', useDate: '' },
    { word: 'jaded', useDate: '' },
    { word: 'geese', useDate: '' },
    { word: 'blind', useDate: '' }
]