require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'wordlegame' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'wordlegameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
    # targetsToFix = ["EXConstants-EXConstants"];
    # installer.generated_projects.each do |project|
    #   project.targets.each do |target|
    #     if targetsToFix.include? target.name
    #       puts "Set development team for target #{target.name}"
    #       target.build_configurations.each do |config|
    #         config.build_settings["DEVELOPMENT_TEAM"] = ""
    #         config.build_settings["CODE_SIGN_IDENTITY"] = "Apple Distribution";
    #         config.build_settings["CODE_SIGN_STYLE"] = "Manual";
    #       end
    #     end
    #   end
    # end

end